# Generated by Django 3.2.21 on 2023-09-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qualquer_coisa',
                'ordering': ['-data', 'titulo'],
                'unique_together': {('titulo', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postagem')),
            ],
        ),
    ]
