# Generated by Django 4.2.5 on 2023-09-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conta",
            fields=[
                ("id_conta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_conta",
                    models.CharField(
                        choices=[("Poupança", "Poupança"), ("Corrente", "Corrente")],
                        max_length=30,
                    ),
                ),
                ("id_banco", models.IntegerField()),
                (
                    "banco",
                    models.CharField(
                        choices=[
                            ("Banco 1", "Banco 1"),
                            ("Banco 2", "Banco 2"),
                            ("Banco 3", "Banco 3"),
                            ("Banco 4", "Banco 4"),
                        ],
                        max_length=7,
                    ),
                ),
                ("conta", models.IntegerField()),
                ("agencia", models.IntegerField()),
                ("operacao", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id_endereco", models.AutoField(primary_key=True, serialize=False)),
                ("nome_cidade", models.TextField(max_length=50)),
                ("observacoes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeFederativa",
            fields=[
                ("id_uf", models.AutoField(primary_key=True, serialize=False)),
                ("nome_uf", models.TextField(max_length=30)),
                ("sigla_uf", models.TextField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.TextField(max_length=30)),
                ("first_name", models.TextField(max_length=30)),
                ("last_name", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id_pessoa", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vinculo",
                    models.CharField(
                        choices=[
                            ("Vinculo 1", "Vinculo 1"),
                            ("Vinculo 2", "Vinculo 2"),
                        ],
                        max_length=9,
                    ),
                ),
                ("cpf", models.IntegerField()),
                ("nome", models.TextField(max_length=200)),
                ("telefone", models.TextField(max_length=16)),
                ("email", models.EmailField(max_length=254)),
                (
                    "auth_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="historico.user"
                    ),
                ),
                (
                    "contas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historico.conta",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historico.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("id_ocorrencia", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField(auto_now_add=True)),
                ("realizada", models.TextField(max_length=1)),
                ("ocorrencia", models.TextField()),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historico.pessoa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="endereco",
            name="cidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="historico.unidadefederativa",
            ),
        ),
    ]
