# Generated by Django 4.2.5 on 2023-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("historico", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="realizada",
            field=models.CharField(max_length=1),
        ),
    ]
